apiVersion: v1
kind: Service
metadata:
  lables:
    app: springbootapp
  name: springbootapp
spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
        app: springbootapp
